--liquibase formatted sql

--changeset AnaAmorim:0005
--comment: insert values to leitor table
INSERT INTO LEITOR VALUES (0001, 'ANA AMORIM', 'ANAAMORIM@HOTMAIL.COM');
INSERT INTO LEITOR VALUES (0002, 'TESSALIA TAU', 'TESSTAU@GMAIL.COM');
INSERT INTO LEITOR VALUES (0003, 'MARIANAF', 'MARIF@HOTMAIL.COM.COM');
--rollback TRUNCATE TABLE LEITOR;