--liquibase formatted sql

--changeset AnaAmorim:0004
--comment: create constraints for historico table
ALTER TABLE HISTORICO ADD CONSTRAINT PK_HIST PRIMARY KEY (ID_LIVRO, ID_LEITOR);
ALTER TABLE HISTORICO ADD CONSTRAINT FK_LIV_HIST FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO(ID_LIVRO);
ALTER TABLE HISTORICO ADD CONSTRAINT FK_LEI_HIST FOREIGN KEY (ID_LEITOR) REFERENCES LEITOR(ID_LEITOR);
--rollback DROP CONSTRAINT FK_LIV_HIST;
--rollback DROP CONSTRAINT FK_LEI_HIST;